version: "3.7"

services:
    app-backend:
        build:
            args:
                user: it-delta
                uid: 1000
            context: .
            dockerfile: docker/app/backend/Dockerfile
        container_name: chromakopia-backend
        restart: unless-stopped
        working_dir: /var/www/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - PHP_IDE_CONFIG=serverName=chromakopia
            - XDEBUG_SESSION=PHPSTORM
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        networks:
            - chromakopia

    app-frontend:
        image: node:latest
        container_name: chromakopia-frontend
        working_dir: /var/www
        ports:
            - "5173:5173"  # Проброс порта для Vite
        volumes:
            - ./:/var/www
        command: sh -c "yarn install && yarn dev"
        networks:
            - chromakopia

    db:
        image: mysql:8.0
        container_name: chromakopia-db
        restart: always
        environment:
            MYSQL_DATABASE: chromakopia
            MYSQL_ROOT_PASSWORD: 123
        volumes:
            - ./tmp/db:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        ports:
            - "3361:3306"
        networks:
            - chromakopia

    nginx:
        image: nginx:latest
        container_name: chromakopia-nginx
        restart: unless-stopped
        ports:
            - "8181:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app-backend
        networks:
            - chromakopia

    supervisor:
        container_name: chromakopia-supervisor
        build:
            context: .
            dockerfile: docker/supervisor/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/supervisor/conf.d/:/etc/supervisor/conf.d/
        working_dir: /var/www
        restart: always
        networks:
            - chromakopia

networks:
    chromakopia:
